language: python
python:
    - '3.8'

install:
    - pip install -r ./requirements.txt
    - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

env:
    - PYTHONPATH=/home/travis/build/alisha-bhatia/hotspot
    - PATH=/home/travis/build/alisha-bhatia/hotspot

script:
    - make tests

#deploy to heroku on push to master
deploy:
    - provider: heroku
      #api_key: $HEROKU_API_KEY
      api_key: 92a28ac8-3a56-4f37-817e-671bb43c527f
      app: teamhotspot
      on:
          branch: master
